name: edit_plus
description: Useful editing widgets that enhance built-in flutter widgets.
version: 1.04.11
author: Jonas Obara

# CHANGELOG
# 08.01.25 - Added UiUtils - Several utilities for working with flutter UI
# 13.02.25 - Added EditplusLocalstorage - Several utilities for working with local files
# 09.03.25 - Added EditplusCollectionUtils - Several utilities for working with dart collections
# 09.03.25 - Moved EditplusUtils to Utils folder
# 29.03.25 - Added the Nutable and associated widgets

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: 0.20.2

# connectivity
  http: 1.3.0

# local data storage
  shared_preferences: ^2.2.2
  path_provider: 2.1.5
  file: 7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
